### ISSUE TITLE
兄弟看到在MI-EEG-1D中的留言，能否交流一下

### ISSUE THREAD

**Issue by leoeooe** [zewail-liu/MyEEG#1]

**Comment by leoeooe** [comment]
https://github.com/Kubasinska/MI-EEG-1D-CNN就是这篇

**Comment by leoeooe** [comment]
> 最近发现JNE上有好多篇这样的文章

**Comment by zewail-liu** [comment]
不好意思刚刚看到，挺同意你的观点的。
感觉现阶段想出好结果需要从预处理数据增强，到后面的模型和调参相互配合，还只能针对小的固定的数据集。。
我也刚刚入门，多多指教🙏

**Comment by leoeooe** [comment]
同学可以加个好友，共同学习吗，qq 792526389
